import { PostType } from '../post';
import { user } from './user';

export const posts: Array<PostType> = [
  {
    '@context': '/contexts/Post',
    '@id': '/posts/1',
    '@type': 'hydra:Item',
    description: 'Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet',
    type: 'LOST',
    state: false,
    location: 'Fake street 123',
    image: '/marliese-streefland-2l0CWTpcChI-unsplash.jpg',
    imageUrl: '/marliese-streefland-2l0CWTpcChI-unsplash.jpg',
    created_at: '2022-04-17T11:33:08+00:00',
    updated_at: '2022-04-17T11:33:08+00:00',
    owner: user,
  },
  {
    '@context': '/contexts/Post',
    '@id': '/posts/2',
    '@type': 'hydra:Item',
    description: 'Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet',
    type: 'LOST',
    state: false,
    location: 'Fake street 123',
    image: '/marliese-streefland-2l0CWTpcChI-unsplash.jpg',
    imageUrl: '/marliese-streefland-2l0CWTpcChI-unsplash.jpg',
    created_at: '2022-04-17T11:33:08+00:00',
    updated_at: '2022-04-17T11:33:08+00:00',
    owner: user,
  },
  {
    '@context': '/contexts/Post',
    '@id': '/posts/3',
    '@type': 'hydra:Item',
    description: 'Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet',
    type: 'LOST',
    state: false,
    location: 'Fake street 123',
    image: '/marliese-streefland-2l0CWTpcChI-unsplash.jpg',
    imageUrl: '/marliese-streefland-2l0CWTpcChI-unsplash.jpg',
    created_at: '2022-04-17T11:33:08+00:00',
    updated_at: '2022-04-17T11:33:08+00:00',
    owner: user,
  },
  {
    '@context': '/contexts/Post',
    '@id': '/posts/4',
    '@type': 'hydra:Item',
    description: 'Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet',
    type: 'LOST',
    state: false,
    location: 'Fake street 123',
    image: '/marliese-streefland-2l0CWTpcChI-unsplash.jpg',
    imageUrl: '/marliese-streefland-2l0CWTpcChI-unsplash.jpg',
    created_at: '2022-04-17T11:33:08+00:00',
    updated_at: '2022-04-17T11:33:08+00:00',
    owner: user,
  },
  {
    '@context': '/contexts/Post',
    '@id': '/posts/5',
    '@type': 'hydra:Item',
    description: 'Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet',
    type: 'LOST',
    state: false,
    location: 'Fake street 123',
    image: '/marliese-streefland-2l0CWTpcChI-unsplash.jpg',
    imageUrl: '/marliese-streefland-2l0CWTpcChI-unsplash.jpg',
    created_at: '2022-04-17T11:33:08+00:00',
    updated_at: '2022-04-17T11:33:08+00:00',
    owner: user,
  },
  {
    '@context': '/contexts/Post',
    '@id': '/posts/6',
    '@type': 'hydra:Item',
    description: 'Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet',
    type: 'LOST',
    state: false,
    location: 'Fake street 123',
    image: '/marliese-streefland-2l0CWTpcChI-unsplash.jpg',
    imageUrl: '/marliese-streefland-2l0CWTpcChI-unsplash.jpg',
    created_at: '2022-04-17T11:33:08+00:00',
    updated_at: '2022-04-17T11:33:08+00:00',
    owner: user,
  },
  {
    '@context': '/contexts/Post',
    '@id': '/posts/7',
    '@type': 'hydra:Item',
    description: 'Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet',
    type: 'LOST',
    state: false,
    location: 'Fake street 123',
    image: '/marliese-streefland-2l0CWTpcChI-unsplash.jpg',
    imageUrl: '/marliese-streefland-2l0CWTpcChI-unsplash.jpg',
    created_at: '2022-04-17T11:33:08+00:00',
    updated_at: '2022-04-17T11:33:08+00:00',
    owner: user,
  },
  {
    '@context': '/contexts/Post',
    '@id': '/posts/8',
    '@type': 'hydra:Item',
    description: 'Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet',
    type: 'LOST',
    state: false,
    location: 'Fake street 123',
    image: '/marliese-streefland-2l0CWTpcChI-unsplash.jpg',
    imageUrl: '/marliese-streefland-2l0CWTpcChI-unsplash.jpg',
    created_at: '2022-04-17T11:33:08+00:00',
    updated_at: '2022-04-17T11:33:08+00:00',
    owner: user,
  },
];
